services:
  - type: web
    name: gp-tsm-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r backend/requirements.txt && python -m spacy download en_core_web_sm && python backend/download_models.py
    startCommand: "python backend/main.py"
    envVars:
      - key: PORT
        value: 10000
